{
    "type": "bundle",
    "id": "bundle--1c14e903-8076-4048-b0f7-c72524b61d72",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--6c032d63-1c17-402f-8ed5-931c9bb5d931",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-11-22T00:20:52.131312Z",
            "modified": "2024-11-22T00:20:52.131312Z",
            "name": "CVE-2024-53432",
            "description": "While parsing certain malformed PLY files, PCL version 1.14.1 crashes due to an uncaught std::out_of_range exception in PCLPointCloud2::at. This issue could potentially be exploited to cause a denial-of-service (DoS) attack when processing untrusted PLY files.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-53432"
                }
            ]
        }
    ]
}