{
    "type": "bundle",
    "id": "bundle--85bbfac9-c110-4fb6-bb0b-e4e57ee7ccda",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--b352fdbd-6fb5-4ac6-8aa7-803ef113ccf7",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-04T00:20:55.36114Z",
            "modified": "2025-04-04T00:20:55.36114Z",
            "name": "CVE-2025-32051",
            "description": "A flaw was found in libsoup. The libsoup soup_uri_decode_data_uri() function may crash when processing malformed data URI. This flaw allows an attacker to cause a denial of service (DoS).",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-32051"
                }
            ]
        }
    ]
}