{
    "type": "bundle",
    "id": "bundle--61afcef2-967e-4e88-80b6-14af224ae0ce",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--ff529e17-7088-40e0-92d2-d957bddc6179",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-01-17T00:19:20.385762Z",
            "modified": "2025-01-17T00:19:20.385762Z",
            "name": "CVE-2018-25108",
            "description": "An unauthenticated remote attacker can cause a DoS in the controller due toÂ uncontrolled resource consumption.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2018-25108"
                }
            ]
        }
    ]
}