{
    "type": "bundle",
    "id": "bundle--7a8cc218-5043-4d47-92b3-f9ac3fa92097",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--5a8d57fa-1e2d-4641-b997-3a25897c61f1",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-03-31T00:22:34.990277Z",
            "modified": "2025-03-31T00:22:34.990277Z",
            "name": "CVE-2025-2953",
            "description": "A vulnerability, which was classified as problematic, has been found in PyTorch 2.6.0+cu124. Affected by this issue is the function torch.mkldnn_max_pool2d. The manipulation leads to denial of service. An attack has to be approached locally. The exploit has been disclosed to the public and may be used.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-2953"
                }
            ]
        }
    ]
}