{
    "type": "bundle",
    "id": "bundle--adfb03bc-52b1-485a-9e1f-d9413a4734b1",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--6eb52476-a5dc-4408-a616-dde04ddeed01",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-03T00:20:54.196714Z",
            "modified": "2025-04-03T00:20:54.196714Z",
            "name": "CVE-2025-2999",
            "description": "A vulnerability was found in PyTorch 2.6.0. It has been rated as critical. Affected by this issue is the function torch.nn.utils.rnn.unpack_sequence. The manipulation leads to memory corruption. Attacking locally is a requirement. The exploit has been disclosed to the public and may be used.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-2999"
                }
            ]
        }
    ]
}