{
    "type": "bundle",
    "id": "bundle--be6baab0-f4f4-48c9-b66c-786921287362",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--bdac687e-d28b-497e-8c56-63c49e7b1b01",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-04T00:20:55.362445Z",
            "modified": "2025-04-04T00:20:55.362445Z",
            "name": "CVE-2025-32049",
            "description": "A flaw was found in libsoup. The SoupWebsocketConnection may accept a large WebSocket message, which may cause libsoup to allocate memory and lead to a denial of service (DoS).",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-32049"
                }
            ]
        }
    ]
}