{
    "type": "bundle",
    "id": "bundle--8499660b-7bd9-4bd3-8718-7349da3ad8bb",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--747733ef-6729-42f8-9743-2a5de24bea8f",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-05-10T00:21:09.141829Z",
            "modified": "2025-05-10T00:21:09.141829Z",
            "name": "CVE-2025-37845",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\ntracing: fprobe events: Fix possible UAF on modules\n\nCommit ac91052f0ae5 (\"tracing: tprobe-events: Fix leakage of module\nrefcount\") moved try_module_get() from __find_tracepoint_module_cb()\nto find_tracepoint() caller, but that introduced a possible UAF\nbecause the module can be unloaded before try_module_get(). In this\ncase, the module object should be freed too. Thus, try_module_get()\ndoes not only fail but may access to the freed object.\n\nTo avoid that, try_module_get() in __find_tracepoint_module_cb()\nagain.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-37845"
                }
            ]
        }
    ]
}