{
    "type": "bundle",
    "id": "bundle--e486b808-04d9-4792-9a25-de6a245677db",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--7a637356-f340-4938-a4cb-12a7a0c25167",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-15T00:22:01.830613Z",
            "modified": "2025-04-15T00:22:01.830613Z",
            "name": "CVE-2025-32914",
            "description": "A flaw was found in libsoup, where the soup_multipart_new_from_message() function is vulnerable to an out-of-bounds read. This flaw allows a malicious HTTP client to induce the libsoup server to read out of bounds.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-32914"
                }
            ]
        }
    ]
}